-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) as 'YEAR', 
MAXSIZE - SIZE_OF_COLONY as 'YEAR_DEV', ID
FROM ECOLI_DATA a JOIN 
(SELECT MAX(SIZE_OF_COLONY) as 'MAXSIZE', YEAR(DIFFERENTIATION_DATE) as 'YEAR'
       FROM ECOLI_DATA
       GROUP BY YEAR(DIFFERENTIATION_DATE)) b on b.YEAR = YEAR(a.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;
